# Site settings
title: The Map Academy â€” CARTO
description: >
  Understand how location intelligence and big data tools work with CARTO Academy documentation and training programs
keywords: "data visualization tools, CARTO. location intelligence, big data, learning resources, deep insights"
baseurl: '/academy'
url: 'https://carto.com'

# Variables
bldr: 'Builder'
crto: 'CARTO'

# Build settings
source: '_app'
destination: '_site/academy'
markdown: kramdown
permalink: pretty
gems:
  - jekyll-redirect-from

# Permalinks
cartodb-baseurl: 'https://carto.com'
blog-baseurl: 'https://carto.com/blog'
github-baseurl: 'https://github.com/CartoDB/academy'

# analytics_property_id: ''
hubspot_id: 474999

# Collections
collections:
  beginners-course:
    output: true
    published: true
    difficulty: easy
    title: "Online Mapping for Beginners"
    url: /courses/beginners-course/
    description: >
      Learn how to work with data tables to create interactive map visualizations.
  design-for-beginners:
    output: true
    published: true
    difficulty: easy
    title: "Introduction to Map Design"
    url: /courses/design-for-beginners/
    description: >
      Start learning the basics of design with data and maps.
  sql-postgis:
    output: true
    published: true
    difficulty: easy
    title: "SQL and PostGIS in CARTO"
    url: /courses/sql-postgis/
    description: >
      Discover the power of SQL and PostGIS by exploring CARTO.
  academy-lite:
    output: true
    published: true
    difficulty: easy
    title: "Academy Lite"
    url: /courses/academy-lite/
    description: >
      Five minute lessons on basic skills for map creation.
  cartojs-ground-up:
    output: true
    published: true
    difficulty: medium
    title: "CARTO.js from the ground up"
    url: /courses/cartojs-ground-up/
    description: >
      Take advantage of the flexibility of CARTO.js to create custom webpages.
  # rapid-map-prototyping:
  #   output: true
  #   published: false
  #   difficulty: TBD
  #   title: "Rapid Map Prototyping"
  #   url: /courses/rapid-map-prototyping/
  #   description: >
  #     TBD
  intermediate-design:
    output: true
    published: true
    difficulty: medium
    title: "Intermediate Map Design"
    url: /courses/intermediate-design/
    description: >
      Learn more about cartography and the pros and cons of thematic map types.
  cartojs-and-external-apis:
    output: true
    published: true
    difficulty: advanced
    title: "CARTO.js and External APIs"
    url: /courses/cartojs-and-external-apis/
    description: >
      This course shows how to use CARTO's JavaScript library CARTO.js with external libraries and APIs.
  community:
    output: true
    published: true
    difficulty: mixed
    title: "Community Content"
    url: /courses/community/
    description: >
      Tutorials from CARTO's community
  builder-intro:
    output: true
    published: true
    difficulty: easy
    title: "Builder Intro"
    url: /courses/builder-intro/
    description: >
      Introduction to CARTO's Builder
defaults:
  - scope:
      path: ""
      type: beginners-course
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: design-for-beginners
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: sql-postgis
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: academy-lite
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: cartojs-ground-up
    values:
      layout: lesson
      body_class: 'js-Lesson'
  # - scope:
  #     path: ""
  #     type: rapid-map-prototyping
  #   values:
  #     layout: lesson
  #     body_class: 'js-Lesson'
  - scope:
      path: ""
      type: intermediate-design
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: cartojs-and-external-apis
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: community
    values:
      layout: lesson
      boty_class: 'js-Lesson'
  - scope:
      path: ""
      type: builder-intro
    values:
      layout: lesson
      boty_class: 'js-Lesson'
